version: '3.6'
networks:
  rede:
    name: redeTeste
services:
    postgres:
        networks:
            - rede
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    localstack:
        image: localstack/localstack:0.10.3
        expose:
          - 4572
        ports:
          - 4572:4572
          - 7070:7070
        networks:
            - rede
        environment:
          - SERVICES=s3
          - DATA_DIR=${DATA_DIR-/tmp/localstack/data}
          - PORT_WEB_UI=7070
        volumes:
          - ./s3:/tmp/localstack
          - "/var/run/docker.sock:/var/run/docker.sock"

    airflow_web:
        image: airflow_java
        restart: always
        depends_on:
            - postgres
            - localstack
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AWS_ACCESS_KEY_ID=XXX
            - AWS_SECRET_ACCESS_KEY=XXX
            - ARROW_PRE_0_15_IPC_FORMAT=1
#            - AIRFLOW_CONN_SPARK_TEST=spark://172.18.0.1:7077
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./s3:/usr/local/airflow/s3
            - ${PWD}/requirements.txt:/requirements.txt
        ports:
            - "8080:8080"
        networks:
            - rede
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3


    spark-master:
      image: teste_spark
      command: spark-class org.apache.spark.deploy.master.Master -h spark-master
      hostname: spark-master
      environment:
        MASTER: spark://spark-master:7077
        SPARK_CONF_DIR: /conf
        SPARK_PUBLIC_DNS: localhost
        ARROW_PRE_0_15_IPC_FORMAT: 1
      expose:
        - 7001
        - 7002
        - 7003
        - 7004
        - 7005
        - 7077
        - 6066
      ports:
        - 4040:4040
        - 6066:6066
        - 7077:7077
#        - 8080:8080
      networks:
        - rede
      volumes:
        - ./conf/master:/conf
        - ./data:/tmp/data

    spark-worker-1:
      image: teste_spark
      command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
      hostname: worker
      environment:
        SPARK_CONF_DIR: /conf
        SPARK_WORKER_CORES: 2
        SPARK_WORKER_MEMORY: 1g
        SPARK_WORKER_PORT: 8881
        SPARK_WORKER_WEBUI_PORT: 8081
        SPARK_PUBLIC_DNS: localhost
        ARROW_PRE_0_15_IPC_FORMAT: 1
      expose:
        - 7012
        - 7013
        - 7014
        - 7015
        - 8881
      ports:
        - 8081:8081
      networks:
        - rede
      volumes:
        - ./conf/worker:/conf
        - ./data:/tmp/data

    spark-worker-2:
      image: teste_spark
      command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
      hostname: worker
      environment:
        SPARK_CONF_DIR: /conf
        SPARK_WORKER_CORES: 2
        SPARK_WORKER_MEMORY: 1g
        SPARK_WORKER_PORT: 8882
        SPARK_WORKER_WEBUI_PORT: 8082
        SPARK_PUBLIC_DNS: localhost
        ARROW_PRE_0_15_IPC_FORMAT: 1
      expose:
        - 7012
        - 7013
        - 7014
        - 7015
        - 8882
      ports:
        - 8082:8082
      networks:
        - rede
      volumes:
        - ./conf/worker:/conf
        - ./data:/tmp/data